name: multimodal_env
channels:
  - conda-forge
  - pytorch 
  - python 
  - defaults 
  - anaconda 
dependencies:
  - python=3.10
  - lxml
  - pillow
  - matplotlib
  - pip
  - pip:
      - langchain
      - openai
      - langchain-chroma
      - langchain-experimental
      - "unstructured[all-docs]==0.10.19"
      - pydantic
      - tiktoken
      - open_clip_torch
      - torch
      - protobuf==3.20.*
